import { Country } from "./country"

export const Cities: Record<Country, string[]> = {
  "USA": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Dallas",
    "Houston",
    "Washington",
    "Miami",
    "Philadelphia",
    "Atlanta",
    "Boston",
    "San Francisco",
    "Phoenix",
    "Riverside",
    "Detroit",
    "Seattle",
    "Minneapolis",
    "San Diego",
    "Tampa",
    "Denver",
    "St. Louis",
    "Baltimore",
    "Orlando",
    "San Antonio",
    "Portland",
    "Sacramento",
    "Pittsburgh",
    "Las Vegas",
    "Cincinnati",
    "Kansas City",
    "Indianapolis",
    "Cleveland",
    "Columbus",
    "Austin",
    "Nashville",
    "Virginia Beach",
    "Jacksonville",
    "Waukesha",
    "Memphis",
    "Louisville",
    "Richmond",
    "Providence",
    "New Orleans",
    "Raleigh",
    "Hartford",
    "Salt Lake City",
    "Oklahoma City",
    "Grand Rapids",
    "Birmingham"
  ],
  "Japan": [
    "Tokyo",
    "Osaka",
    "Nagoya",
    "Kyoto",
    "Fukuoka",
    "Kobe",
    "Sapporo",
    "Sendai",
    "Okayama",
    "Hiroshima"
  ],
  "Mexico": [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Toluca",
    "Tijuana",
    "León",
    "Juárez",
    "Zapopan",
    "Mérida"
  ],
  "Canada": [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener"
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
    "Changwon",
    "Goyang"
  ],
  "Puerto Rico": [
    "San Juan",
    "Ponce",
    "Mayagüez"
  ],
  "Cuba": [
    "Havana",
    "Santiago de Cuba",
    "Camagüey"
  ]
}